param(
    [string]$PublicBaseUrl = "https://pello.xincreates.com",
    [int]$Port = 3003,
    [string]$HostName = "0.0.0.0",
    [string]$DataFile = "",
    [string]$ApkPath = "",
    [string]$AdminToken = "",
    [string]$AdminTokenFile = "",
    [string]$AdminPath = "",
    [string]$AdminPathFile = "",
    [switch]$StartLocal,
    [switch]$SkipBuild,
    [switch]$WriteEnv,
    [string]$EnvPath = "",
    [switch]$UnlockAppServer
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$configPath = Join-Path $root "shared\competitive-config.json"

if (-not (Test-Path $configPath)) {
    throw "Missing shared competitive config: $configPath"
}

if (-not $SkipBuild) {
    Push-Location $root
    try {
        npm run build
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
    } finally {
        Pop-Location
    }
}

$config = Get-Content $configPath -Raw | ConvertFrom-Json
$table = $config.tables | Select-Object -First 1

if (-not $DataFile) {
    $DataFile = Join-Path $root "server\data\competitive-state.json"
}

if (-not $AdminTokenFile) {
    $AdminTokenFile = Join-Path $root "server\data\admin-token.txt"
}
if (-not [System.IO.Path]::IsPathRooted($AdminTokenFile)) {
    $AdminTokenFile = Join-Path $root $AdminTokenFile
}
if (-not $AdminToken) {
    if (Test-Path -LiteralPath $AdminTokenFile) {
        $AdminToken = (Get-Content -LiteralPath $AdminTokenFile -Raw).Trim()
    } else {
        $tokenBytes = New-Object byte[] 24
        $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
        try {
            $rng.GetBytes($tokenBytes)
        } finally {
            $rng.Dispose()
        }
        $AdminToken = ([System.BitConverter]::ToString($tokenBytes) -replace "-", "").ToLowerInvariant()
        $tokenDir = Split-Path -Parent $AdminTokenFile
        if ($tokenDir) {
            New-Item -ItemType Directory -Force -Path $tokenDir | Out-Null
        }
        Set-Content -LiteralPath $AdminTokenFile -Value $AdminToken -Encoding ASCII
    }
}

if (-not $AdminPathFile) {
    $AdminPathFile = Join-Path $root "server\data\admin-path.txt"
}
if (-not [System.IO.Path]::IsPathRooted($AdminPathFile)) {
    $AdminPathFile = Join-Path $root $AdminPathFile
}
if (-not $AdminPath) {
    if (Test-Path -LiteralPath $AdminPathFile) {
        $AdminPath = (Get-Content -LiteralPath $AdminPathFile -Raw).Trim()
    } else {
        $pathBytes = New-Object byte[] 8
        $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
        try {
            $rng.GetBytes($pathBytes)
        } finally {
            $rng.Dispose()
        }
        $pathSuffix = ([System.BitConverter]::ToString($pathBytes) -replace "-", "").ToLowerInvariant()
        $AdminPath = "/admin-$pathSuffix.html"
        $pathDir = Split-Path -Parent $AdminPathFile
        if ($pathDir) {
            New-Item -ItemType Directory -Force -Path $pathDir | Out-Null
        }
        Set-Content -LiteralPath $AdminPathFile -Value $AdminPath -Encoding ASCII
    }
}
if (-not $AdminPath.StartsWith("/")) {
    $AdminPath = "/$AdminPath"
}
if ($AdminPath -notmatch '^/[A-Za-z0-9/_-]+(\.html)?$') {
    throw "Invalid admin path: $AdminPath. Use characters A-Z, a-z, 0-9, slash, underscore, dash, and optional .html."
}
$AdminUrlPath = $AdminPath
if ($AdminUrlPath.EndsWith(".html")) {
    $AdminUrlPath = $AdminUrlPath.Substring(0, $AdminUrlPath.Length - 5)
}

if (-not $ApkPath) {
    $repoApk = Join-Path $root "public\download\Pello.apk"
    $androidApk = Join-Path $root "android\app\build\outputs\apk\debug\app-debug.apk"
    $ApkPath = if (Test-Path $repoApk) { $repoApk } else { $androidApk }
}

function Get-LanAddress {
    $candidate = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
        Where-Object {
            $_.IPAddress -notlike "127.*" -and
            $_.IPAddress -notlike "169.254.*" -and
            $_.PrefixOrigin -ne "WellKnown"
        } |
        Select-Object -First 1

    if ($candidate) {
        return $candidate.IPAddress
    }

    return "127.0.0.1"
}

if ($PublicBaseUrl) {
    $httpBase = $PublicBaseUrl.TrimEnd("/")
} else {
    $httpBase = "http://$(Get-LanAddress):$Port"
}

$wsBase = $httpBase -replace "^https://", "wss://" -replace "^http://", "ws://"
$healthUrl = "$httpBase/api/competitive/health"
$adminUrl = "$httpBase$AdminUrlPath"
$adminAlternateUrl = "$httpBase$AdminPath"
$appServerLocked = if ($UnlockAppServer) { "false" } else { "true" }
$envLines = @(
    "# Generated by scripts/deploy-app-server.ps1",
    "VITE_PELLO_SERVER_URL=$httpBase",
    "VITE_PELLO_SERVER_LOCKED=$appServerLocked"
)
$resolvedEnvPath = $null

if ($WriteEnv) {
    if (-not $EnvPath) {
        $EnvPath = Join-Path $root ".env.production.local"
    } elseif (-not [System.IO.Path]::IsPathRooted($EnvPath)) {
        $EnvPath = Join-Path $root $EnvPath
    }

    $resolvedEnvPath = $EnvPath
    $envDir = Split-Path -Parent $resolvedEnvPath
    if ($envDir) {
        New-Item -ItemType Directory -Force -Path $envDir | Out-Null
    }
    Set-Content -Path $resolvedEnvPath -Value $envLines -Encoding UTF8
}

$serverProcess = $null
if ($StartLocal) {
    $existing = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
    if (-not $existing) {
        $node = (Get-Command node).Source
        $logDir = Join-Path $root ".tools"
        New-Item -ItemType Directory -Force -Path $logDir | Out-Null
        $outLog = Join-Path $logDir "app-server.out.log"
        $errLog = Join-Path $logDir "app-server.err.log"

        $env:NODE_ENV = "production"
        $env:PORT = "$Port"
        $env:HOST = $HostName
        $env:PELLO_COMPETITIVE_STORE = $DataFile
        $env:PELLO_APK_PATH = $ApkPath
        $env:PELLO_ADMIN_TOKEN = $AdminToken
        $env:PELLO_ADMIN_PATH = $AdminPath

        $serverProcess = Start-Process -FilePath $node `
            -ArgumentList "server/server.js" `
            -WorkingDirectory $root `
            -RedirectStandardOutput $outLog `
            -RedirectStandardError $errLog `
            -WindowStyle Hidden `
            -PassThru

        Start-Sleep -Seconds 2
    }

    $localHealth = "http://127.0.0.1:$Port/api/competitive/health"
    try {
        $response = Invoke-RestMethod -Uri $localHealth -TimeoutSec 5
        if (-not $response.ok) {
            throw "Health endpoint returned ok=false"
        }
    } catch {
        throw "Local app server health check failed at $localHealth. $($_.Exception.Message)"
    }
}

Write-Host ""
Write-Host "=== PELLO APP BACKEND CONFIG ==="
Write-Host "APP_SERVER_HTTP=$httpBase"
Write-Host "APP_SERVER_WS=$wsBase"
Write-Host "APP_HEALTH_URL=$healthUrl"
Write-Host "APP_APK_URL=$httpBase/download/Pello.apk"
Write-Host "APP_ADMIN_URL=$adminUrl"
Write-Host "APP_ADMIN_ALTERNATE_URL=$adminAlternateUrl"
Write-Host "APP_ADMIN_LOGIN_TOKEN=$AdminToken"
Write-Host "APP_ADMIN_TOKEN=$AdminToken"
Write-Host "APP_ADMIN_TOKEN_FILE=$AdminTokenFile"
Write-Host "APP_ADMIN_PATH=$AdminPath"
Write-Host "APP_ADMIN_PATH_FILE=$AdminPathFile"
Write-Host "APP_CURRENCY=$($config.currency)"
Write-Host "APP_INITIAL_COINS=$($config.initialCoins)"
Write-Host "APP_COMPETITIVE_TABLE_ID=$($table.id)"
Write-Host "APP_COMPETITIVE_STAKE=$($table.stake)"
Write-Host "APP_COMPETITIVE_WINNER_PAYOUT=$($table.winnerPayout)"
Write-Host "APP_AI_FALLBACK_TIMEOUT_MS=$($table.matchmakingTimeoutMs)"
Write-Host "APP_AI_DAILY_REWARD_LIMIT=$($config.ai.dailyRewardLimit)"
Write-Host ""
Write-Host "=== ANDROID APP VITE ENV ==="
foreach ($line in $envLines) {
    if ($line -notlike "#*") {
        Write-Host $line
    }
}
if ($resolvedEnvPath) {
    Write-Host "APP_ENV_PATH=$resolvedEnvPath"
}
Write-Host ""
Write-Host "=== SERVER ENV ==="
Write-Host "NODE_ENV=production"
Write-Host "HOST=$HostName"
Write-Host "PORT=$Port"
Write-Host "PELLO_COMPETITIVE_STORE=$DataFile"
Write-Host "PELLO_APK_PATH=$ApkPath"
Write-Host "PELLO_ADMIN_TOKEN=$AdminToken"
Write-Host "PELLO_ADMIN_PATH=$AdminPath"
Write-Host ""
Write-Host "=== START COMMAND ==="
Write-Host "npm run build"
Write-Host "`$env:NODE_ENV=`"production`"; `$env:PORT=`"$Port`"; `$env:HOST=`"$HostName`"; `$env:PELLO_COMPETITIVE_STORE=`"$DataFile`"; `$env:PELLO_APK_PATH=`"$ApkPath`"; `$env:PELLO_ADMIN_TOKEN=`"$AdminToken`"; `$env:PELLO_ADMIN_PATH=`"$AdminPath`"; npm run server:start"
Write-Host ""
Write-Host "=== ANDROID APP NOTE ==="
Write-Host "For internal-test APKs, write the Vite env above before building. For a physical Android phone, use this computer's LAN URL, not localhost."
Write-Host "Production APKs should keep VITE_PELLO_SERVER_LOCKED=true and use a public HTTPS backend URL."

if ($serverProcess) {
    Write-Host ""
    Write-Host "LOCAL_SERVER_PID=$($serverProcess.Id)"
}
